FROM openjdk:8-jre-alpine

COPY allure-2.7.0.tgz /

RUN mkdir -p /allure-results 

RUN apk update \
    && apk add tar \
    && tar -xvf allure-2.7.0.tgz \
    && chmod -R +x /allure-2.7.0/ \
    && rm -f allure-2.7.0.tgz

WORKDIR /allure-2.7.0/bin

VOLUME ["/allure-results"]

EXPOSE 8800

CMD [ "./allure","serve","/allure-results","-p","8800" ]