FROM node:8

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./



RUN npm install
# If you are building your code for production
# RUN npm install --only=production

#I odon't know why this wasn't being installed with 
RUN npm install -g protractor
# Bundle app source
COPY . .

RUN chmod -R 777 .


VOLUME [ "/usr/src/app/Tests" ]

EXPOSE 8080
CMD [ "npm", "test" ]